services:
  superset:
      build:
        context: ./superset
        dockerfile: dockerfile
      restart: always
      container_name: superset
      environment: 
        - ADMIN_USERNAME=admin
        - ADMIN_EMAIL=admin@superset.com
        - ADMIN_PASSWORD=admin
      ports:
        - '8088:8088'
  postgres: 
      build: 
        context: ./postgresql
        dockerfile: dockerfile
      restart: always
      environment:
        POSTGRES_USER: superset_user
        POSTGRES_DB: superset_db
        POSTGRES_PASSWORD: example
      volumes:
        - "/mnt/Lukas/superset/pgdata:/var/lib/postgresql/data"
      ports:
        - '5432:5432'
